name: 'blog feed ci'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.feed.outputs.changed }}
      items: ${{ steps.feed.outputs.items }}
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: |
            https://denisthiessen.de/feed.xml
            https://microrss.denisthiessen.de/rss.xml
          file: 'README.md'
          max_entry: 5
          format: <li>${monthshort} ${02day} ~ <a href="${url}">${title}</a></li>
      - name: push to master
        if: steps.feed.outputs.changed == true
        id: commit
        uses: sarisia/actions-commit@master
        with:
          message: "updated feed"  
